[variables]
NODE_VERSION = "22"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmd = "NODE_ENV=production node dist/index.js"

[start]
cmd = "NODE_ENV=production node dist/index.js"